// examples/banner/angular/src/banner/banner.component.ts
import { Component, Input } from '@angular/core';
import { ContentBody, Image } from 'dc-delivery-sdk-js';

export interface Banner extends ContentBody {
  headline: string;
  strapline: string;
  background: {
    image: Image;
    alt: string;
  };
  link: {
    title: string;
    url: string;
  };
}
@Component({
  selector: 'app-banner',
  templateUrl: './banner.component.html',
  styleUrls: ['./banner.component.css'],
})
export class BannerComponent {
  @Input() banner!: Banner;
}

<section class="banner">
  <header>
    <h1>{{ banner.headline }}</h1>
    <h2>{{ banner.strapline }}</h2>
  </header>
  <img
    src="{{ banner.background.image.url().build() }}"
    alt="{{ banner.background.alt }}"
  />
  <a href="{{ banner.link.url }}">
    {{ banner.link.title }}
  </a>
</section>

// banner/react/src/Components/Banner.js
import React from 'react';
import './banner.css';

const Banner = ({ headline, strapline, background = {}, link = {} }) => {
  return (
    <section className="banner">
      <header>
        <h1>{headline}</h1>
        <h2>{strapline}</h2>
      </header>
      <img src={background.image?.url().build()} alt={background.alt} />
      <a href={link.url}>{link.title}</a>
    </section>
  );
};

export default Banner;
