// banner/angular/src/banner/banner.component.ts
import { Component, Input } from '@angular/core';
import { ContentBody, Image } from 'dc-delivery-sdk-js';

export interface Banner extends ContentBody {
  headline: string;
  strapline: string;
  background: {
    image: Image;
    alt: string;
  }
  link: {
    title: string,
    url: string
  }
}
@Component({
  selector: 'app-banner',
  templateUrl: './banner.component.html',
  styleUrls: ['./banner.component.css'],
})
export class BannerComponent {
  @Input() banner!: Banner;
}

<section class="banner">
  <header>
    <h1>{{ banner?.title }}</h1>
    <h2>{{ banner?.subtitle }}</h2>
  </header>
  <img
    src="{{ banner?.image?.url().width(1200).height(680).build() }}"
    alt=""
  />
  <a href="{{ banner?.link.url }}">
    {{ banner?.link.title }}
  </a>
</section>

// banner/react/src/Components/Banner.js
import React from 'react';
import './banner.css';

const Banner = ({ title, subtitle, image, link = {} }) => {
  const src = image?.url().width(1200).height(680).build();

  return (
    <section className="banner">
      <header>
        <h1>{title}</h1>
        <h2>{subtitle}</h2>
      </header>
      <img src={src} alt="" />
      <a href={link.url}>{link.title}</a>
    </section>
  );
};

export default Banner;
