// banner/react/src/App.js
import './styles.css';
import React, { useEffect, useState } from 'react';
import { ContentClient } from 'dc-delivery-sdk-js';
import Banner from './Components/Banner';

const client = new ContentClient({
  hubName: 'ampengineering',
});

const deliveryKey = 'example-banner';

export default function App() {
  const [banner, setBanner] = useState();

  useEffect(() => {
    async function fetchBanner() {
      const banner = await client.getContentItemByKey(deliveryKey);

      setBanner(banner.body);
    }

    fetchBanner();
  }, []);

  return banner && <Banner {...banner} />;
}

// banner/vue/src/App.vue
<template>
  <Banner v-if="banner" v-bind="banner" />
</template>

<script>
import { ContentClient } from 'dc-delivery-sdk-js';
import BannerVue from './components/Banner.vue';
export default {
  name: 'App',
  components: {
    Banner: BannerVue,
  },
  async created() {
    await this.fetchBanner();
  },
  data: function () {
    return {
      client: new ContentClient({ hubName: 'ampengineering' }),
      deliveryKey: 'banner-example',
      banner: null,
    };
  },
  methods: {
    async fetchBanner() {
      const { body } = await this.client.getContentItemByKey(this.deliveryKey);
      this.banner = body;
    },
  },
};
</script>
