// examples/banner/svelte/src/Banner.svelte
<script>
  export let headline;
  export let strapline;
  export let background;
  export let link;
</script>

<section class="banner">
  <header>
    <h1>{headline}</h1>
    <h2>{strapline}</h2>
  </header>
  <img src={background.image.url().build()} alt={background.alt} />
  <a href={link?.url}>{link?.title}</a>
</section>

<style>
@import url(https://fonts.googleapis.com/css?family=Roboto);

.banner {
  font-family: IBM Plex Sans, Arial, Helvetica, sans-serif;
  position: relative;
  width: 100%;
  min-width: 500px;
}

.banner h1 {
  font-family: IBM Plex serif;
  font-size: 48px;
  font-weight: 400;
  background-color: #000c42aa;
  padding:12px;
  width:56%;
}

.banner h2 {
  font-size: 16px;
  font-weight: 400;
  background-color: #000c42aa;
  padding:12px;
  width:56%;
}

.banner header {
  position: absolute;
  top: 0px;
  width: 100%;
  padding: 0 24px;
  text-align: left;
  color: white;
}

.banner img {
  width: 100%;
  height: auto;
}

.banner a {
  position: absolute;
  bottom: 40px;
  background-color: #000c42;
  font-weight: 400;
  color: white;
  left: 24px;
  padding: 16px;
  text-decoration: none;
}

.banner a:hover {
  background-color: rgba(50, 139, 241);
  color: white;

}
</style>

// examples/banner/vue/src/components/Banner.vue
<template>
  <section>
    <header>
      <h1>{{ headline }}</h1>
      <h2>{{ strapline }}</h2>
    </header>
    <img :src="background.image.url().build()" :alt="background.alt" />
    <a :href="link.url">
      {{ link.title }}
    </a>
  </section>
</template>

<script>
export default {
  name: 'BannerComponent',
  props: {
    headline: String,
    strapline: String,
    background: Object,
    link: Object,
  },
};
</script>

<style scoped>
@import url(https://fonts.googleapis.com/css?family=Roboto);

.banner {
  font-family: IBM Plex Sans, Arial, Helvetica, sans-serif;
  position: relative;
  width: 100%;
  min-width: 500px;
}

.banner h1 {
  font-family: IBM Plex serif;
  font-size: 48px;
  font-weight: 400;
  background-color: #000c42aa;
  padding:12px;
  width:56%;
}

.banner h2 {
  font-size: 16px;
  font-weight: 400;
  background-color: #000c42aa;
  padding:12px;
  width:56%;
}

.banner header {
  position: absolute;
  top: 0px;
  width: 100%;
  padding: 0 24px;
  text-align: left;
  color: white;
}

.banner img {
  width: 100%;
  height: auto;
}

.banner a {
  position: absolute;
  bottom: 40px;
  background-color: #000c42;
  font-weight: 400;
  color: white;
  left: 24px;
  padding: 16px;
  text-decoration: none;
}

.banner a:hover {
  background-color: rgba(50, 139, 241);
  color: white;

}
</style>
`
