// banner/svelte/src/App.svelte
<script>
  import Banner from './Banner.svelte';
  import { onMount } from 'svelte';
  import { ContentClient } from 'dc-delivery-sdk-js';

  let banner = null;

  const client = new ContentClient({
    hubName: 'ampengineering',
  });

  const deliveryKey = 'example-banner';

  async function fetchBanner() {
    banner = await client.getContentItemByKey(deliveryKey);
  }

  onMount(() => fetchBanner());
</script>

<main>
  {#if banner}
    <Banner {...banner.body} />
  {/if}
</main>

// banner/react/src/App.js
import './styles.css';
import React, { useEffect, useState } from 'react';
import { ContentClient } from 'dc-delivery-sdk-js';
import Banner from './Banner';

const client = new ContentClient({
  hubName: 'ampengineering',
});

const deliveryKey = 'banner-example';

export default function App() {
  const [banner, setBanner] = useState(null);

  useEffect(() => {
    async function fetchBanner() {
      const banner = await client.getContentItemByKey(deliveryKey);

      setBanner(banner.body);
    }

    fetchBanner();
  }, []);

  return banner && <Banner {...banner} />;
}
